language: ruby
sudo: false

rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - jruby
  - truffleruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: truffleruby
    - rvm: ruby-head
  fast_finish: true

install:
  - gem install bundler:2.0.1
  - bundle install
