language: ruby
sudo: false

before_install:
 - gem update --system
 - gem install bundler
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby
  - truffleruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: truffleruby
    - rvm: ruby-head
  fast_finish: true
