language: ruby
sudo: false

rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - jruby
  - truffleruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: truffleruby
    - rvm: ruby-head
  fast_finish: true

install:
  - gem install bundler:2.0.2
  - bundle install
