language: ruby
sudo: false

before_install:
 - gem update --system
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.0
  - jruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
  fast_finish: true
