language: ruby
sudo: false

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - jruby
  - truffleruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: truffleruby
    - rvm: ruby-head
  fast_finish: true

install:
  - gem install bundler:2.0.2
  - bundle install
